### PR TITLE
CP-1211 Upgrade to gulp-connect 2.3.1

### PR DESCRIPTION
**Pull request by maxwellpeterson-wf**
>Just a heads-up that the `gulp-connect` packaged required in `wGulp` has some broken stuff in its latest release which affects Smithy builds.  There is a new release in the pipeline, however: https://github.com/AveVlad/gulp-connect/releases/tag/2.3.1  Fix was released 12 minutes ago.

Reported by @jimhotchkin-wf 

## Changes
**Source:**
- Update gulp-connect dependency

## Testing
- CI Passes
- @jimhotchkin-wf would you be able to supply a testing +10 for this PR?

## Code Review
@trentgrover-wf
@evanweible-wf 
@dustinlessard-wf
FYI @jayudey-wf

### CODE REVIEW

**Comment by jimhotchkin-wf** [comment]
Testing +10 : Smithy builds no longer error out.  Local builds pull down expected version of gulp-connect @ 2.3.1.

Just wondering if you have considered pinning the versions of these packages?

Thanks!

**Comment by trentgrover-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - performed and documented by Jim Hotchkin
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Comment by travisreed-wf** [comment]
rosie

**Pull request merged**
