### PR TITLE
CP-440 Release wGulp 0.7.8

### PR DESCRIPTION
**Pull request by jayudey-wf**
PRs contained in this release:

https://github.com/Workiva/wGulp/pull/131

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/wGulp/compare/0.7.7...Release_0.7.8

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
+1

**Comment by rmconsole-wf** [comment]
When this pull is merged I will not be able to function
		properly because no valid release_tickets exist for
		repo: Workiva/wGulp. Please create a ticket with the title: RELEASE wGulp 0.7.9
		If your team does not use JIRA, please specify this in rmconsole options.

***
*Last updated on Friday, March 06 10:25 AM CST*

**Comment by evanweible-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
go @rmconsole-wf

**Comment by teresarevious-wf** [comment]
@rmconsole-wf

**Comment by jayudey-wf** [comment]
go @rmconsole-wf

**Comment by teresarevious-wf** [comment]
@rmconsole-wf

**Comment by teresarevious-wf** [comment]
@rmconsole-wf

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
