### PR TITLE
CP-621 Release wGulp 0.8.3

### PR DESCRIPTION
**Pull request by jayudey-wf**
PRs contained in this release:

https://github.com/Workiva/wGulp/pull/151

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/wGulp/compare/0.8.2...Release_0.8.3

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Comment by travisreed-wf** [comment]
@rosie run_merge_script

**Comment by teresarevious-wf** [comment]
RM +1

**Pull request merged**
