### PR TITLE
CP-967 Release wGulp 0.8.5

### PR DESCRIPTION
**Pull request by jayudey-wf**
PRs contained in this release:

https://github.com/Workiva/wGulp/pull/158
https://github.com/Workiva/wGulp/pull/161

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/wGulp/compare/0.8.4...Release_0.8.5

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
CI fail

**Comment by jayudey-wf** [comment]
@trentgrover-wf passing CI

**Comment by trentgrover-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Comment by travisreed-wf** [comment]
rosie

**Pull request merged**
