### PR TITLE
CP-1002 update license text and karma-jspm dependency

### PR DESCRIPTION
**Pull request by trentgrover-wf**
## Issue
- outdated OSS license text
- outdated karma-jspm dependency

## Changes
**Source:**
- docs only change

**Tests:**
- no changes

## Areas of Regression
- karma-jspm test runs

## Testing
- CI is happy
- test karma-jspm run on a consumer app

## Code Review
@maxwellpeterson-wf
@evanweible-wf
@dustinlessard-wf 
@jayudey-wf

### CODE REVIEW

**Comment by evanweible-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by dustinlessard-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - installed into a consumer app and verified that tests were able to be run as expected
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Comment by travisreed-wf** [comment]
rosie

**Pull request merged**
