### PR TITLE
CP-456 Release wGulp 0.8.0

### PR DESCRIPTION
**Pull request by jayudey-wf**
PRs contained in this release:

https://github.com/Workiva/wGulp/pull/130
https://github.com/Workiva/wGulp/pull/134
https://github.com/Workiva/wGulp/pull/139

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/wGulp/compare/0.7.8...Release_0.8.0

### CODE REVIEW

**Comment by rmconsole-wf** [comment]
When this pull is merged I will use the following information:
		Version: wGulp 0.8.0
		Release Ticket: CP-456

		This pull is considered the release of wGulp 0.8.0. 
		The options defined for this repo will be carried out

***
*Last updated on Monday, March 09 03:33 PM CST*

**Comment by evanweible-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
