### PR TITLE
CP-329 Release wGulp 0.7.5

### PR DESCRIPTION
**Pull request by charliekump-wf**
PRs contained in this release:

https://github.com/Workiva/wGulp/pull/120
https://github.com/Workiva/wGulp/pull/121

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/wGulp/compare/0.7.4...Release_0.7.5

How To +10/QA
-------------

```bash
# skip the following steps if you've already initialized the project
git clone git@github.com:Workiva/wGulp.git
cd wGulp

# do not skip these!
git fetch && git checkout Release_0.7.5
Run unit tests
```

### CODE REVIEW

**Comment by rmconsole-wf** [comment]
When this pull is merged I will use the following information:
		Version: wGulp 0.7.5
		Release Ticket: CP-329

		This pull is considered the release of wGulp 0.7.5. 
		This repo will be tagged, release notes will be created, and communication will go out.

***
*Last updated on Tuesday, January 13 04:29 PM CST*

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by charliekump-wf** [comment]
QA Resource Approval: +1

- [x] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
