### PR TITLE
WP-5915 Release wGulp 0.8.5-unit-test-only

### PR DESCRIPTION
**Pull request by aaronlademann-wf**
This PR creates a parallel line-of-release for this (mostly) deprecated library to unblock certain consumers.

Consumers who do not have the ability to install scoped packages, which the intern dependency uses. 

This will provide them a workaround until they have that capability

@maxwellpeterson-wf @evanweible-wf

### CODE REVIEW

**Review by maxwellpeterson-wf — APPROVED** [review]

**Comment by aviary2-wf** [comment]
## Raven
<details>
<summary>Number of Findings: 0</summary>

</details>

## Magpie
<details>
<summary>Number of findings: 0</summary>

</details>

**Review by maxwellpeterson-wf — APPROVED** [review]

**Comment by maxwellpeterson-wf** [comment]
+10
- CI passes

**Comment by maxwellpeterson-wf** [comment]
QA +1
- [x] Dev +1's
- [x] Dev/QA +10 with detail of what was tested
  - https://github.com/Workiva/wGulp/pull/164#issuecomment-363198849
- [ ] Tests created/updated 
- [x] All tests pass

Merging.

**Comment by aaronlademann-wf** [comment]
@rmconsole-wf

**Comment by teresarevious-wf** [comment]
RM +1 - https://github.com/Workiva/wGulp/compare/0.8.5...0.8.5-unit-test-only Rosie is now configured for branch releases, verified this release manually

**Pull request merged**
