### PR TITLE
CP-534 Release wGulp 0.8.2

### PR DESCRIPTION
**Pull request by jayudey-wf**
PRs contained in this release:

https://github.com/Workiva/wGulp/pull/147

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/wGulp/compare/0.8.1...Release_0.8.2

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1

- [ ] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Comment by teresarevious-wf** [comment]
RM +1

**Pull request merged**
