### PR TITLE
CP-457 Upgrade to typescript1.4

### PR DESCRIPTION
**Pull request by maxwellpeterson-wf**
## Description

Typescript 1.4 adds some new features (such as union types, improved compile times) that wGulp consumers will want to use. This PR upgrades the typescript dependency version so that wGulp can take advantage of the new compiler.

## Testing

The new compiler emits slightly different results, so we needed to update some of our test fixtures. Those updates are included. Existing unit tests should cover the changes.

* Existing unit tests pass
* Able to build typescript projects (wSession, wService, etc) with this branch of wGulp

### CODE REVIEW

**Comment by rmconsole-wf** [comment]
When this pull is merged I will not be able to function
		properly because no ticket is included in the title.
		If your team has decided not to use jira please indicate this in rmconsole

***
*Last updated on Monday, March 02 04:40 PM CST*

**Comment by trentgrover-wf** [comment]
@maxwellpeterson-wf @evanweible-wf all fixed

**Comment by maxwellpeterson-wf** [comment]
+1 nice!

**Comment by evanweible-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
go @rmconsole-wf

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - unit tests pass, typescript projects still able to build
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Pull request merged**
