### PR TITLE
CP-458 Pin gulp-livereload and tiny-lr dependencies

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Issue
At some point, an update to gulp-livereload and/or tiny-lr caused `gulp watch:test` tasks to fail when running in PhantomJS. These versions are the culprits:
```
› npm list | grep gulp-livereload
  ├─┬ gulp-livereload@2.1.1

› npm list | grep tiny-lr
  │ └─┬ tiny-lr@0.1.5
```

This is the error you will see:
```
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Mac OS X)]: Connected on socket B1lI2gdGivbzw6IH8qNL with id 20798968
PhantomJS 1.9.8 (Mac OS X) ERROR
  Script error.
```

## Solution
Pin gulp-livereload and tiny-lr:

```
› npm list | grep gulp-livereload
  ├─┬ gulp-livereload@2.1.0

› npm list | grep tiny-lr
  ├─┬ tiny-lr@0.0.7
```

## Testing
- All tests pass
- Consumer of wGulp can install this branch and run `gulp watch:test` successfully

---

fya: @trentgrover-wf @maxwellpeterson-wf

### CODE REVIEW

**Comment by rmconsole-wf** [comment]
When this pull is merged I will not be able to function
		properly because no ticket is included in the title.
		If your team has decided not to use jira please indicate this in rmconsole

***
*Last updated on Friday, March 06 03:19 PM CST*

**Comment by trentgrover-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
go @rmconsole-wf

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
 - verified that task was able to be run successfully with this change
- [ ] Unit test created/updated
- [ ] All unit tests pass

Merging into master.

**Pull request merged**
